In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
data = pd.read_csv("C:/Users/karagiag/Downloads/GLD.csv",parse_dates = True)

In [3]:
data.set_index('Date')

,Open,High,Low,Close,Adj Close,Volume
Date,,,,,,
03/01/2011,138.669998,139.000000,137.880005,138.000000,138.000000,11510200
04/01/2011,136.240005,136.279999,134.160004,134.750000,134.750000,26154300
05/01/2011,133.500000,134.679993,133.100006,134.369995,134.369995,16700900
06/01/2011,134.050003,134.380005,133.139999,133.830002,133.830002,15965300
07/01/2011,133.380005,134.610001,133.179993,133.580002,133.580002,16761400
10/01/2011,133.850006,134.199997,133.240005,134.119995,134.119995,8429900
11/01/2011,134.789993,135.160004,133.960007,134.910004,134.910004,10268400
12/01/2011,134.789993,135.580002,134.350006,135.460007,135.460007,10785100
13/01/2011,135.660004,135.679993,133.630005,134.050003,134.050003,14294600
14/01/2011,133.169998,133.600006,132.220001,132.690002,132.690002,21224900
18/01/2011,133.630005,134.000000,133.169998,133.429993,133.429993,11592900
19/01/2011,134.339996,134.399994,133.399994,133.720001,133.720001,11788100
20/01/2011,131.759995,132.100006,131.039993,131.199997,131.199997,24362900
21/01/2011,130.759995,131.429993,130.529999,131.029999,131.029999,19488400
24/01/2011,131.009995,131.630005,130.139999,130.360001,130.360001,15127200
25/01/2011,129.649994,130.270004,129.070007,130.100006,130.100006,22219700
26/01/2011,129.830002,131.169998,129.279999,131.160004,131.160004,20543000
27/01/2011,130.289993,130.490005,127.800003,127.930000,127.930000,33047000
28/01/2011,127.970001,131.479996,127.949997,130.279999,130.279999,28091500
31/01/2011,129.270004,130.509995,129.250000,129.869995,129.869995,14664100
01/02/2011,130.520004,131.080002,129.330002,130.800003,130.800003,15363700
02/02/2011,130.369995,130.600006,129.449997,130.449997,130.449997,10082000
03/02/2011,130.070007,132.320007,129.279999,132.199997,132.199997,17374700
04/02/2011,131.839996,132.699997,131.229996,131.660004,131.660004,15214300
07/02/2011,131.669998,131.949997,131.229996,131.679993,131.679993,7176300
08/02/2011,132.960007,133.500000,132.800003,133.139999,133.139999,16220900
09/02/2011,133.190002,133.389999,132.490005,133.070007,133.070007,10178400
10/02/2011,132.110001,133.309998,132.000000,132.850006,132.850006,8105200
11/02/2011,133.009995,133.440002,132.089996,132.320007,132.320007,9888600
14/02/2011,132.949997,133.380005,132.699997,132.949997,132.949997,8694200
...,...,...,...,...,...,...
19/09/2016,125.610001,125.620003,125.250000,125.320000,125.320000,4959600
20/09/2016,125.309998,125.589996,125.169998,125.440002,125.440002,5672000
21/09/2016,126.330002,127.419998,125.959999,127.269997,127.269997,13646400
22/09/2016,127.570000,128.199997,127.500000,127.570000,127.570000,15188000
23/09/2016,127.599998,127.860001,127.430000,127.650002,127.650002,7702300
26/09/2016,127.959999,128.039993,127.419998,127.550003,127.550003,5842700
27/09/2016,126.860001,126.900002,126.339996,126.620003,126.620003,6220700
28/09/2016,126.250000,126.400002,125.730003,126.220001,126.220001,6757700
29/09/2016,125.839996,126.339996,125.540001,126.070000,126.070000,7448400
30/09/2016,126.519997,126.550003,125.239998,125.639999,125.639999,11204300
03/10/2016,125.320000,125.459999,124.900002,125.320000,125.320000,9044100
04/10/2016,123.160004,123.180000,120.860001,120.970001,120.970001,24372700
05/10/2016,121.330002,121.589996,120.400002,120.779999,120.779999,14718100
06/10/2016,119.690002,119.980003,119.239998,119.660004,119.660004,17917700
07/10/2016,120.489998,120.580002,118.419998,119.739998,119.739998,17907300
10/10/2016,119.739998,120.419998,119.739998,120.160004,120.160004,4514400
11/10/2016,119.919998,120.160004,119.529999,119.550003,119.550003,6065300
12/10/2016,119.720001,120.070000,119.290001,119.739998,119.739998,4848600
13/10/2016,120.000000,120.419998,119.800003,120.029999,120.029999,7184600
14/10/2016,119.370003,120.160004,119.290001,119.360001,119.360001,6577300
17/10/2016,119.699997,119.919998,119.580002,119.680000,119.680000,4777900
18/10/2016,120.080002,120.639999,119.820000,120.419998,120.419998,4919700
19/10/2016,121.129997,121.459999,120.889999,121.110001,121.110001,6019800
20/10/2016,121.389999,121.589996,120.629997,120.739998,120.739998,6496700
21/10/2016,120.900002,120.930000,120.550003,120.830002,120.830002,6707800
24/10/2016,121.279999,121.300003,120.160004,120.559998,120.559998,5481100
25/10/2016,120.889999,121.760002,120.860001,121.470001,121.470001,6141100
26/10/2016,121.370003,121.529999,120.610001,120.790001,120.790001,3905900
27/10/2016,121.110001,121.180000,120.750000,121.010002,121.010002,4336000
28/10/2016,121.199997,122.480003,120.809998,121.580002,121.580002,11639900

In [4]:
data.rename(columns={'Adj Close': 'price'}, inplace=True)

In [5]:
data['returns']=np.log(data['price']/data['price'].shift(1))

In [6]:
SMA=50 #Moving Average Rolling Window

In [7]:
data['SMA']=data['price'].rolling(SMA).mean()

In [8]:
threshold = 10

In [9]:
data['distance']= data['price']-data['SMA']

In [10]:
data['distance'].dropna().plot(figsize=(10,6), legend=True)
plt.axhline(threshold, color='r')
plt.axhline(-threshold, color='r')
plt.axhline(0,color='r')

In [11]:
plt.show()

In [145]:
#If the distance value is greater than the threshold value go short (set -1 in the new column position) 
#otherwise set NaN.
data['position'] = np.where(data['distance']> threshold,-1,np.nan)

In [146]:
#If the distance value is lower than the negative threshold value go long (set 1)
#otherwise keep the column position unchanged.
data['position'] = np.where(data['distance']< -threshold,1,data['position'])

In [147]:
#If there is a change in the sign of the distance value go market neutral (set 0)
#otherwise keep the column position unchanged.
data['position'] = np.where(data['distance'] * data['distance'].shift(1) < 0, 0, data['position'])

In [148]:
#Forward fill all NaN position with the previous values; replace all remaining NaN values by 0.
data['position'] = data['position'].ffill().fillna(0)

In [149]:
data['position'].ix[SMA:].plot(figsize=(10, 6))

In [150]:
plt.show()

In [151]:
data['strategy']= data['position'].shift(1)*data['returns']

In [161]:
data[['returns', 'strategy']].dropna().cumsum().apply(np.exp).plot(figsize=(10, 6))

In [162]:
plt.show()